const zoningStyles = [
  {
    id: 'zoning',
    source: 'zoning-data',
    type: 'fill',
    paint: {
      'fill-color': [
        'match',
        ['get', 'zone_type'],
        1,
        '#0000ff',
        2,
        '#0000ff',
        3,
        '#ffff00',
        4,
        '#00ff00',
        5,
        '#ff0000',
        6,
        '#ffff00',
        7,
        '#0000ff',
        8,
        '#0000ff',
        9,
        '#00ff00',
        10,
        '#0000ff',
        11,
        '#666666',
        12,
        '#38761d',
        '#000000', // Default color if no match
      ],
      'fill-opacity': [
        'step',
        ['zoom'],
        0.35,
        14,
        [
          'case',
          ['in', '1', ['get', 'zone_class']],
          0.15,
          ['in', '1.5', ['get', 'zone_class']],
          0.15,
          ['in', '2', ['get', 'zone_class']],
          0.25,
          ['in', '3', ['get', 'zone_class']],
          0.35,
          ['in', '3.5', ['get', 'zone_class']],
          0.45,
          ['in', '4', ['get', 'zone_class']],
          0.45,
          ['in', '4.5', ['get', 'zone_class']],
          0.55,
          ['in', '5', ['get', 'zone_class']],
          0.55,
          ['in', '5.5', ['get', 'zone_class']],
          0.6,
          ['in', '6', ['get', 'zone_class']],
          0.6,
          ['in', '7', ['get', 'zone_class']],
          0.6,
          ['in', '12', ['get', 'zone_class']],
          0.65,
          ['in', '16', ['get', 'zone_class']],
          0.65,
          ['in', 'P', ['get', 'zone_class']],
          0.35,
          0.35, // Default opacity
        ],
      ],
    },
  },
  {
    id: 'zoning-outline',
    source: 'zoning-data',
    type: 'line',
    paint: {
      'line-opacity': [
        'case',
        ['==', ['feature-state', 'clicked'], true],
        1,
        0.25,
      ],
      'line-width': [
        'case',
        ['==', ['feature-state', 'clicked'], true],
        1.5,
        0.25,
      ],
    },
  },
]
